#------------------------------------------------------------#
#                     HorseOwners config                     #
#------------------------------------------------------------#

# Should the server keep track of horses' ranking?
# WARNING: Setting to false will clear existing rank data
rank-claimed-horses: true

# Should the server also record stats of unclaimed horses?
# WARNING: Requires rank-claimed-horses to also be true
rank-unclaimed-horses: true

# Should the server keep track of horses' locations?
# WARNING: Setting to false will clear existing coordinate data
save-horse-coordinates: true

# Should the server keep track of horses' parents?
# WARNING: Setting to false will clear existing lineage data
save-horse-lineage: true

# Allow players to "lock" a horse's name
# WARNING: Setting to false will clear existing name-lock data
enable-name-locks: true

# A list of the types of "Horses" players can claim
# WARNING: Removing entities from this list will prevent future
# claims but NOT delete existing claims of these entities!
valid-horses:
  - HORSE
  - DONKEY
  - MULE
  - LLAMA

# Enable this to allow players to teleport leashed mobs
# (when destination is in same world)
teleport-leashed-mobs: true

# Enable this to only allow named mobs to be teleported
# (encourages nametag use)
teleport-leashed-mobs-if-named: true

# Enable this to teleport owned horses that are within 4 blocks
# of the player who is teleporting
teleport-unleashed-owned-horses: true

# Disable this to disable ALL horse (and entity) teleportation
# done through this plugin
enable-teleporting: true

# Disable this to allow players to teleport horses to
# "unsafe" locations (i.e., 1x2 block tunnel)
teleport-only-if-safe: true

# Disable this to prevent ALL trans-world horse teleportation
teleport-across-worlds: true

# Safest to keep this set to true
names-mostly-alphanumeric: true

# Specify whether players must have a nametag to claim/rename horses
nametag-required-to-rename: false

# Already named horses are automatically claimed when tamed
claim-on-tame: true

# Modify breeding to enable configuration of max jump, speed, and health
modified-breeding: true

# These are currently set to the default minecraft values
max-jump: 5.5
max-speed: 13.5
max-health: 30

# Assigns a random name to a new foal at birth. Requires modified-breeding is true
name-at-birth: false

# Automatically claims newly born foals. Requires name-at-birth and modified-breeding are true
claim-at-birth: true

# If this foal's parents are owned by different players, who does it belong to?
# Possible values are: MOTHER, FATHER, RANDOM. Requires that claim-at-birth is true
owner-at-birth-is-owner-of: RANDOM

# Prevent chunks with claimed horses from being unloaded
# while the horses' owner is online
keep-horse-chunks-in-memory: true

# Fix fall damage glitch that occurs when riding a horse
# with a strong jump characteristic
reduce-fall-damage: true

# Prevent players from unleashing horses they do not own
prevent-lead-breaking: true

# Prevent players from breaking fences for horses
# they do not own that are leashed to the fence.
prevent-lead-fence-breaking: false

# Allows players to leash mobs not normally leashable, such as
# Zombies, Creepers, Silverfish, and Squids
leash-other-mobs: true

# Should players be able to feed someone else's (claimed) horse?
feed-private-horse: true

# Should players be able to breed someone else's (claimed) horse?
breed-private-horse: true

# Should players be able to ride someone else's (claimed) horse?
ride-private-horse: false

# Should players be able to hurt someone else's (claimed) horse?
attack-private-horse: true

# Should players be able to look at chests on someone else's
# (claimed) horse?
snoop-private-horse: false

# Enable this if you plan on frequently editing the horses.yml file
# while the server is running. It ensure your edits do not get
# overwritten, but may slow down some commands (minor lag).
config-update-checking: false

min-name-length: 3
max-name-length: 15

# Command Prices:
# if you want players to have to pay to use some (or all)
# of the commands in this plugin, simply add
# "[commandname]: [price]" as done in these examples:
# 
# allowride: 0
# claimhorse: 100
# freehorse: 0
# gethorse: 10
# inspecthorse: 0
# listhorses: 1
# lockhorse: 25
# spawnhorse: 250
# unleashhorse: 0
# Note: Supports economies through Vault and EssentialsEco.
# If you don't have one of these installed, this won't work
# Use the permission "evp.horseowners.commands.free" to make
# a player exempt from having to pay for commands.