name: HorseOwners
main: net.evmodder.HorseOwners.HorseManager
Author: EvModder
version: 2.7.3 #7=/hm top [stat] [page], x.3=rewrite of updateData(Entity)
api-version: 1.13

commands:
   horsemanager:
      description: HorseManager commands & info
      usage: /hm ?
      aliases: [horsemang,hm]
      permission: horseowners.commands
      permission-message: You do not have permission to do this.

   allowride:
      description: Grant one ride
      usage: /hm allowride <Player> [horse]
      aliases: [allow-ride,letride,oneride,unlockride,allowhorse]
      permission: horseowners.allowride
      permission-message: You do not have permission to do this.

   claimhorse:
      description: Claim your steed
      usage: /hm claim [name]
      aliases: [nhorse,namehorse,renamehorse,myhorse,nh]
      permission: horseowners.claim
      permission-message: You do not have permission to do this.

   copyhorse:
      description: Make a copy of a horse
      usage: /hm copy [horse]
      aliases: [pastehorse]
      permission: horseowners.copy
      permission-message: You do not have permission to do this.

   freehorse:
      description: Grant your steed its freedom
      usage: /hm free [horse]
      aliases: [unclaimhorse,releasehorse,freeh,unclaimh]
      permission: horseowners.claim
      permission-message: You do not have permission to do this.

   gethorse:
      description: Teleport one of your horses to you
      usage: /hm get [horse]
      aliases: [fetchorse,fetchhorse,fetch-horse,bringhorse,tphorse,tpherehorse]
      permission: horseowners.tpcommand
      permission-message: You do not have permission to do this.

   inspecthorse:
      description: View speed/health/etc for a horse
      usage: /hm inspect [horse]
      aliases: [horsespeed,shorse,ihorse,horsei,seehorse,horsestats,
      checkhorse,speedh,ihorse,horsei,hstats,hstat,statshorse,viewhorse]
      permission: horseowners.inspect
      permission-message: You do not have permission to do this.

   listhorse:
      description: Veiw a list of horses (& their owners)
      usage: /hm list [@a]
      aliases: [listhorses,horselist,listh,hlist,horses,lhorse]
      permission: horseowners.list
      permission-message: You do not have permission to do this.

   lockhorse:
      description: Give you steed an immutable name.
      usage: /hm lock [horse]
      permission: horseowners.lock
      permission-message: You do not have permission to do this.

   summonshadowfax:
      description: Summon the Lord of all Horses.
      usage: /hm shadowfax
      permission: horseowners.shadowfax
      permission-message: Unknown command

   spawnhorse:
      description: Spawn a custom horse.
      usage: /hm spawn [n:name] [v:variant] [c:color] [t:style] [j:jump] [s:speed] [h:health] [-tamed]
      permission: horseowners.spawn
      permission-message: You do not have permission to do this.

   tophorse:
      description: See the top horses on the server
      usage: /hm ranklist [s/j/h]
      aliases: [ranklisthorse,hranklist,rankhorse,rankshorse,rhorse,hranks]
      permission: horseowners.ranklist
      permission-message: You do not have permission to do this.

   unleashhorse:
      description: Helpful for glitched leash hitches
      usage: /unleash [horse]
      aliases: [unleash-horse,unleashorse,untiehorse,removelead,unleash,clearleash,untie]
      permission: horseowners.unleash
      permission-message: You do not have permission to do this.

permissions:
   horseowners.allowride:
      description: Permission to give a 1-time access of your horse to another player via /letride [Player]
      default: true

   horseowners.claim:
      description: Permission to claim horses.
      default: true

   horseowners.claim.coloredname:
      description: Allow colors and basic formats when naming a horse.
      default: false

   horseowners.claim.allformats:
      description: Allow all formats when naming a horse.
      default: false

   horseowners.copy:
      description: Permission to copy horses
      default: op

   horseowners.tpcommand:
      description: Ability to summon a horse via /fetch-horse [name]
      default: true

   horseowners.crossworld.samegamemode:
      description: Permission to teleport horses between worlds that share the same Gamemode
      default: true

   horseowners.crossworld.*:
      description: Permission to bring horses from any world to any other world via. teleporting.
      default: op

   horseowners.list:
      description: The ability to view a list your claimed horses.
      default: true

   horseowners.list.all:
      description: The ability to print a list of anyone's horses
      default: op

   horseowners.list.unclaimed:
      description: The ability to see a list of even the unclaimed horses
      default: op

   horseowners.lock:
      description: Prevent a horse from being re-named.
      default: true

   horseowners.shadowfax:
      description: The ability to summon Shadowfax.
      default: false

   horseowners.spawn:
      description: The ability to spawn a custom horse.
      default: op

   horseowners.ranklist:
      description: The ability to view a stat ranklist of all horses
      default: true

   horseowners.unleash:
      description: Unleash a horse (useful when the leadhitch doesn't render)
      default: true


# -------------- Permissions not directly tied to a specific command -------------- #
   horseowners.commands:
      description: Permission to use commands.
      default: true

   horseowners.commands.free:
      description: Permission to use commands for free (if prices are set in the config)
      default: false

   horseowners.override:
      description: Permission to access other people's horses
      default: false

   horseowners.inspect.name:
      description: Ability to view a horse's name
      default: op

   horseowners.inspect.rankings:
      description: Ability to view a horse's rankings
      default: op

   horseowners.inspect.owner:
      description: Ability to view a horse's owner
      default: op

   horseowners.inspect.tamer:
      description: Ability to view a horse's tamer
      default: op

   horseowners.inspect.jump:
      description: Ability to view a horse's jump
      default: op

   horseowners.inspect.speed:
      description: Ability to view a horse's speed
      default: op

   horseowners.inspect.lineage:
      description: Ability to view a horse's lineage
      default: op

   horseowners.inspect.coords:
      description: Ability to look up a horse's location
      default: op

   horseowners.inspect:
      description: The ability to view a horse's stats
      children:
         horseowners.inspect.name: true
         horseowners.inspect.rankings: true
         horseowners.inspect.owner: true
         horseowners.inspect.tamer: true
         horseowners.inspect.jump: true
         horseowners.inspect.speed: true
         horseowners.inspect.health: true
         horseowners.inspect.lineage: true
      default: op

   horseowners.inspect.others:
      description: The ability to view another player's horses' stats
      default: true

   horseowners.inspect.unclaimed:
      description: The ability to look up stats for unclaimed horses
      default: op

   horseowners.inspect.untamed:
      description: The ability to look up stats for untamed horses
      children:
         horseowners.inspect.unclaimed: true
      default: op

   horseowners.admin:
      description: Full access to others' horses as well as one's own.
      children:
         horseowners.override: true
         horseowners.commands: true
         horseowners.claim: true
         horseowners.coloredname: true
         horseowners.allformats: true
         horseowners.unleash: true
         horseowners.lock: true
         horseowners.tpcommand: true
         horseowners.crossworld.anywhere: true
         horseowners.crossworld.samegamemode: true
         horseowners.inspect: true
         horseowners.inspect.others: true
         horseowners.inspect.untamed: true
         horseowners.spawn: true
         horseowners.list: true
         horseowners.list.all: true
         horseowners.allowride: true
      default: op
